# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo "Hello from Azure Pipeline 🚀"
    displayName: "Run basic script"

  - script: |
      echo "Build started"
      echo "Listing files"
      ls -la
    displayName: "Build step"
